In [34]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,MaxPool2D,Conv2D,Flatten,MaxPooling2D
import pickle5 as pickle
from customcvfunc import imagesplitter
import numpy as np

pickle_in=open("X.pickle","rb")
X=pickle.load(pickle_in)
pickle_in=open("y.pickle","rb")
y=pickle.load(pickle_in)
print(y[:10])
y = np.array(y)
print(y[:10])
# cat 0 is 0 , cat 5 is 1 , cat 10 is 2

[2, 1, 0, 0, 2, 0, 2, 2, 0, 1]
[2 1 0 0 2 0 2 2 0 1]


In [35]:
# normalise the data
X = X/255  # image 0 to 255
# reshape to match Keras expectaions
X = X.reshape(X.shape[0], 32, 64, 1)
# X = X.reshape(X.shape[0], 32, 64, channels)
# https://medium.com/datadriveninvestor/dual-input-cnn-with-keras-1e6d458cd979

In [36]:
X.shape[1:]
type(y)
y.shape
X.shape

(29390, 32, 64, 1)

In [38]:
#https://keras.io/api/layers/convolution_layers/convolution2d/
# we might want to resize our x from 32 X 64 to 
# define the model
# layer 1
model = Sequential()
model.add( Conv2D( 64, (3,3),input_shape = X.shape[1:]) )
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
# layer 2
model.add( Conv2D(64,(3,3)) )
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add( Conv2D(128,(3,3)) )
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
# layer 3
model.add(Flatten())
model.add(Dense(64))
# activation
model.add(Dense(3))
model.add(Activation('sigmoid'))
# https://www.tensorflow.org/tutorials/keras/save_and_load
model.summary()
#https://www.tensorflow.org/api_docs/python/tf/keras/losses
# metrics the goal what other alternatives can we try/ suitable
model.compile(loss="sparse_categorical_crossentropy",optimizer="adam",metrics=['accuracy'])
model.fit(X,y,batch_size=32,validation_split=0.4,epochs=8)

Epoch 1/8
552/552 [==============================] - 41s 74ms/step - loss: 0.7198 - accuracy: 0.6575 - val_loss: 0.4712 - val_accuracy: 0.8118
Epoch 2/8
552/552 [==============================] - 43s 78ms/step - loss: 0.3306 - accuracy: 0.8708 - val_loss: 0.2928 - val_accuracy: 0.8966
Epoch 3/8
552/552 [==============================] - 44s 79ms/step - loss: 0.2205 - accuracy: 0.9225 - val_loss: 0.1951 - val_accuracy: 0.9361
Epoch 4/8
552/552 [==============================] - 44s 79ms/step - loss: 0.1611 - accuracy: 0.9448 - val_loss: 0.1842 - val_accuracy: 0.9372
Epoch 5/8
552/552 [==============================] - 44s 79ms/step - loss: 0.1305 - accuracy: 0.9555 - val_loss: 0.1652 - val_accuracy: 0.9494
Epoch 6/8
552/552 [==============================] - 44s 79ms/step - loss: 0.1025 - accuracy: 0.9642 - val_loss: 0.1497 - val_accuracy: 0.9571
Epoch 7/8
552/552 [==============================] - 44s 80ms/step - loss: 0.0959 - accuracy: 0.9669 - val_loss: 0.1467 - val_accuracy: 0.9549

In [42]:
# model.save("model.h5") 

In [72]:
# model.predict(X[0])
pred=model.predict(X)
print(pred[0])
y[0]
# we got it working

[2.0667518e-05 1.6517725e-06 6.4036965e-02]


2

In [104]:
type(X[0])
print(X.shape)
print(X[0].shape)
xx=np.array([X[0]])
xx.shape

(29390, 32, 64, 1)
(32, 64, 1)


(1, 32, 64, 1)

In [70]:
pred=model.predict(xx)

In [125]:
import cv2
img = cv2.imread("extracted_data/10/01_123.jpeg",0)

In [126]:
T=[]

In [127]:
T.append(img)

In [129]:
T=np.array(T).reshape(-1,32,64)

In [132]:
T[0].shape


(32, 64)

In [133]:
# normalise the data
T = T/255  # image 0 to 255
# reshape to match Keras expectaions
T = T.reshape(T.shape[0], 32, 64, 1)
# X = X.reshape(X.shape[0], 32, 64, channels)
# https://medium.com/datadriveninvestor/dual-input-cnn-with-keras-1e6d458cd979

In [134]:
T.shape

(1, 32, 64, 1)

In [135]:
p=model.predict(T)

In [136]:
p

array([[0.12415114, 0.0018208 , 0.02656522]], dtype=float32)

In [137]:
type(p)

numpy.ndarray

In [139]:
p[0][0]

0.12415114